# Test deploy
language: java

env:
  - PASS_FROM_SET2="heh"

before_install:
- export BUILD_NUMBER=$TRAVIS_BUILD_NUMBER-$TRAVIS_BUILD_ID
- export DEPL_ENV="bad-branch"
- export PASS_FROM_SET="bedpassword"
- if [[ "$TRAVIS_BRANCH" == "master"* ]]; then export DEPL_ENV="master"; fi
- if [[ "$TRAVIS_BRANCH" == "DEV"* ]]; then export DEPL_ENV="DEV"; PASS_FROM_SET2=$DEV_password; fi

install:
- cp ./build/$DEPL_ENV/build.properties ./build.properties

script:
- ant -buildfile build.xml -Dbuild.number=$BUILD_NUMBER testdeploy
